### ISSUE TITLE
Screenshot tool opened with vertical monitor, freeze frame rotated incorrectly

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-screenshot#46]
When the screenshot tool is opened with a vertical display the freeze frame it shows is rotated as if it's assuming the display is supposed to be horizontal, this is also showing the blacked out half as shown in #45 

![IMG20240813180013](https://github.com/user-attachments/assets/f1d6ced0-9fae-4bc7-a250-40ff945e04aa)

**Comment by freyjadomville** [comment]
I didn't have the energy to report this at the time, but I want to quietly add/confirm this. This behaviour also affects OBS captures of a vertical screen, at least when I tested it last (using the Wayland video bridge, I'm yet to test it since reinstalling my distribution to check if that's still a problem). For me, KDE is fine for vertical monitor captures, so I'm assuming this is additionally related to the Wayland display server itself and not _necessarily_ just the screenshot tool.

**Comment by yari-dog** [comment]
I can also confirm this issue, with my top monitor rotated 1pr,  opening the screenshot tool rotates the monitor back to 0. however; with the screenshot tool still open, pressing the screenshot shortcut a second time causes the screen to rotate back to 1pi, albeit with a 2nd screenshot window added (see pics below).

---
![image](https://github.com/user-attachments/assets/7f0af962-a38f-486d-8806-407f8643e30a)
> pressed once, rotated back to 0pi.
---
![image](https://github.com/user-attachments/assets/479c80a8-109c-4ea3-8a09-1017d6637ba1)
> pressed twice, back to 1pi.
---
![image](https://github.com/user-attachments/assets/c9b6ee9b-89a8-4cd0-9145-2763645cc498)
> screenshot from being pressed once.
---
![image](https://github.com/user-attachments/assets/dfe4c08b-6512-4ae3-bc01-f18d23674d87)
> screenshot from being pressed twice.
