### ISSUE TITLE
Selection capture can create a corrupted screenshot which crashes COSMIC

### ISSUE THREAD

**Issue by BrodieRobertson** [pop-os/cosmic-screenshot#54]
If you attempt to take a screenshot and choose the selection option but instead of selecting an area you instead just click Capture, this will attempt to take a screenshot and a file will be created. This file however is corrupted and if you drag it into an application like GIMP, COSMIC will suddenly crash and restart.

**Comment by joshuamegnauth54** [comment]
Hi! I opened a PR that fixes the first issue where empty selections save invalid files. The PR is [here](https://github.com/pop-os/xdg-desktop-portal-cosmic/pull/95) because the XDG portal backend handles screenshots.

You may want to open a new issue in the [cosmic-comp](https://github.com/pop-os/cosmic-comp) repository for the second problem you found. It seems related to the compositor, and it is more likely that someone will see the issue there as well.
